# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Encfixture < Formula
  desc "Generate dummy media files for ffmpeg encoding tests"
  homepage "https://github.com/junara/encfixture"
  version "0.1.3"
  license "MIT"

  depends_on "ffmpeg"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/junara/encfixture/releases/download/v0.1.3/encfixture_0.1.3_darwin_amd64.tar.gz"
      sha256 "78195e2916576e78e82466abb3a7bd5b3f20f8f84ad10e2c7a43b1979bb42346"

      define_method(:install) do
        bin.install "encfixture"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/junara/encfixture/releases/download/v0.1.3/encfixture_0.1.3_darwin_arm64.tar.gz"
      sha256 "7b9e620a4f20c2e56381035c312bffb6c9d5a64c9b65c5bdf972f19ec6225b33"

      define_method(:install) do
        bin.install "encfixture"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/junara/encfixture/releases/download/v0.1.3/encfixture_0.1.3_linux_amd64.tar.gz"
      sha256 "e7071c1a00c855c45c75a8e64a9f779378201fd7c4b3c5ef82043935bfec3325"
      define_method(:install) do
        bin.install "encfixture"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/junara/encfixture/releases/download/v0.1.3/encfixture_0.1.3_linux_arm64.tar.gz"
      sha256 "4644965a0139546b1578c4a779059808223f91cb9ecb4a8537cb9e86d84e8801"
      define_method(:install) do
        bin.install "encfixture"
      end
    end
  end
end
