# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Encfixture < Formula
  desc "Generate dummy media files for ffmpeg encoding tests"
  homepage "https://github.com/junara/encfixture"
  version "0.1.1"
  license "MIT"

  depends_on "ffmpeg"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/junara/encfixture/releases/download/v0.1.1/encfixture_0.1.1_darwin_amd64.tar.gz"
      sha256 "094226e6988176a9f525d1325d6a075cdedb9b261298130d8bfea715310480b3"

      define_method(:install) do
        bin.install "encfixture"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/junara/encfixture/releases/download/v0.1.1/encfixture_0.1.1_darwin_arm64.tar.gz"
      sha256 "ccb5abd42e2240056090c5b10a9b26de6de72c740f0efb3ab73ef35a7ec0983c"

      define_method(:install) do
        bin.install "encfixture"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/junara/encfixture/releases/download/v0.1.1/encfixture_0.1.1_linux_amd64.tar.gz"
      sha256 "675371c2ef826386c1f1a8ee33b2cc19f1d230d05028bfa7c8f400ade17b06ff"
      define_method(:install) do
        bin.install "encfixture"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/junara/encfixture/releases/download/v0.1.1/encfixture_0.1.1_linux_arm64.tar.gz"
      sha256 "f8402304de07e1350fcbef01b965b38bf14b87750de1c38057da70b9475f2800"
      define_method(:install) do
        bin.install "encfixture"
      end
    end
  end
end
