# This file was generated by GoReleaser. DO NOT EDIT.
cask "encfixture" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "ca6ddc7aacfd029de50078d0060f1684a7494c3cdd8cf5704910b84dafb8f6ca"
      url "https://github.com/junara/encfixture/releases/download/v#{version}/encfixture_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2f23ece90c3ed29c300c73afe57a34c31a116015249170d4663ba0616fbbfdd5"
      url "https://github.com/junara/encfixture/releases/download/v#{version}/encfixture_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "09ae6111320f13666dc8ef215e0970cae2c3593839fc355771632f716096444b"
      url "https://github.com/junara/encfixture/releases/download/v#{version}/encfixture_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "417150f2e8dcb6f47549ad71c68a8748b1720aaa0aaad276e23e89144c1077fd"
      url "https://github.com/junara/encfixture/releases/download/v#{version}/encfixture_#{version}_linux_amd64.tar.gz"
    end
  end

  name "encfixture"
  desc "Generate dummy media files for ffmpeg encoding tests"
  homepage "https://github.com/junara/encfixture"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "encfixture"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/encfixture"]
    end
  end

  # No zap stanza required
end
