# This file was generated by GoReleaser. DO NOT EDIT.
cask "encfixture" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "4aad9872a357202e68ad1cf95482bee567a231fca1e250c6656cfc618370aa10"
      url "https://github.com/junara/encfixture/releases/download/v#{version}/encfixture_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/junara/encfixture/"
    end
    on_arm do
      sha256 "95466bdfcf6c9896faf49ba2a29629a58e74b7791619da55f98de5f8f05d57b8"
      url "https://github.com/junara/encfixture/releases/download/v#{version}/encfixture_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/junara/encfixture/"
    end
  end

  on_linux do
    on_intel do
      sha256 "406ab0d8b9099c7f556bdff0c57b2f98bc46bb443813221760c155427fb6f16f"
      url "https://github.com/junara/encfixture/releases/download/v#{version}/encfixture_#{version}_linux_amd64.tar.gz",
        verified: "github.com/junara/encfixture/"
    end
    on_arm do
      sha256 "9ebd379f3c12cc43ae029938f2555cc2c178b10ad0982134528010d40527bbb1"
      url "https://github.com/junara/encfixture/releases/download/v#{version}/encfixture_#{version}_linux_arm64.tar.gz",
        verified: "github.com/junara/encfixture/"
    end
  end

  name "encfixture"
  desc "Generate dummy media files for ffmpeg encoding tests"
  homepage "https://github.com/junara/encfixture"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "encfixture"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/encfixture"]
    end
  end

  # No zap stanza required

end
