# This file was generated by GoReleaser. DO NOT EDIT.
cask "encfixture" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "b194db0ff72928406a7e9c4d6e8c17558f1d4e5d8711de3220068514fe6c75de"
      url "https://github.com/junara/encfixture/releases/download/v#{version}/encfixture_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/junara/encfixture/"
    end
    on_arm do
      sha256 "3116dd1869e700665ec7cee1bac95dae42e52ac45a3c2a9580bd5e58af31a53e"
      url "https://github.com/junara/encfixture/releases/download/v#{version}/encfixture_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/junara/encfixture/"
    end
  end

  on_linux do
    on_intel do
      sha256 "c77deff1140d9fb03cb21f0aefecc000e7ade2949d381ecde1a5c41511761f44"
      url "https://github.com/junara/encfixture/releases/download/v#{version}/encfixture_#{version}_linux_amd64.tar.gz",
        verified: "github.com/junara/encfixture/"
    end
    on_arm do
      sha256 "60d0cab229cb7205fdef7ba78f5305a75081e3a4b11c3e46ea62ff27d55dfc0a"
      url "https://github.com/junara/encfixture/releases/download/v#{version}/encfixture_#{version}_linux_arm64.tar.gz",
        verified: "github.com/junara/encfixture/"
    end
  end

  name "encfixture"
  desc "Generate dummy media files for ffmpeg encoding tests"
  homepage "https://github.com/junara/encfixture"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "encfixture"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/encfixture"]
    end
  end

  # No zap stanza required

end
