# This file was generated by GoReleaser. DO NOT EDIT.
cask "jheader-proxy" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "113dc9ac5f77c2732f85ce532263d2c624ca7f994ca191e4e173997dee2dbd0d"
      url "https://github.com/junara/jheader-proxy/releases/download/v#{version}/jheader-proxy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5fd6b4cae206d4328603ac6defdcc6424613e4bfb981330b6f7b4436e92b1b78"
      url "https://github.com/junara/jheader-proxy/releases/download/v#{version}/jheader-proxy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ee2223c3721bef2637d5776af62b7304f7df030f5fd8a03d1c12e8c5302f4bab"
      url "https://github.com/junara/jheader-proxy/releases/download/v#{version}/jheader-proxy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "19a91d6b3fe913ae5ec79b39110c2ac2bd67dca7f0ae609fded725c5cec0aa43"
      url "https://github.com/junara/jheader-proxy/releases/download/v#{version}/jheader-proxy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jheader-proxy"
  desc "Local HTTP/HTTPS proxy that adds request headers for target domains (iPhone dev/testing)"
  homepage "https://github.com/junara/jheader-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jheader-proxy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jheader-proxy"]
    end
  end

  # No zap stanza required

end
