# This file was generated by GoReleaser. DO NOT EDIT.
cask "jheader-proxy" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "21a4c20450b949cf12a8e6b6cedd456a5a82398eda47926c20f53e15de3c3126"
      url "https://github.com/junara/jheader-proxy/releases/download/v#{version}/jheader-proxy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e66786c4cabd9355667420cea871ce440b7100fc79fad0871b53809de4254739"
      url "https://github.com/junara/jheader-proxy/releases/download/v#{version}/jheader-proxy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ff5d8c7a36b1387ae8ccd378caa47a58be48a815c943be84d4abdf7e23c795c1"
      url "https://github.com/junara/jheader-proxy/releases/download/v#{version}/jheader-proxy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f1d1245b68a20f1f5d94d2649485121bb0e6d64d6d114f5fea9f0c2773383bc7"
      url "https://github.com/junara/jheader-proxy/releases/download/v#{version}/jheader-proxy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jheader-proxy"
  desc "Local HTTP/HTTPS proxy that adds request headers for target domains (iPhone dev/testing)"
  homepage "https://github.com/junara/jheader-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jheader-proxy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jheader-proxy"]
    end
  end

  # No zap stanza required

end
