# This file was generated by GoReleaser. DO NOT EDIT.
cask "jheader-proxy" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "8d52bf41c758399f3606546e83fbad5cae2826ceb0bf242e1c3a5bc3025d1db0"
      url "https://github.com/junara/jheader-proxy/releases/download/v#{version}/jheader-proxy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8151d80d655398cb4b48cd9ab838f05fa92d5008b28800709d994eb43e93d377"
      url "https://github.com/junara/jheader-proxy/releases/download/v#{version}/jheader-proxy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6842f5b8c7100a795054e537a2e3e8d1efb455d8ba11ed313dd222927d013ede"
      url "https://github.com/junara/jheader-proxy/releases/download/v#{version}/jheader-proxy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0113393bbdf05f2423b578cccf370a81e6045f6d85e37818e4346d98bcc0cc0f"
      url "https://github.com/junara/jheader-proxy/releases/download/v#{version}/jheader-proxy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jheader-proxy"
  desc "Local HTTP/HTTPS proxy that adds request headers for target domains (iPhone dev/testing)"
  homepage "https://github.com/junara/jheader-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jheader-proxy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jheader-proxy"]
    end
  end

  # No zap stanza required

end
