# This file was generated by GoReleaser. DO NOT EDIT.
cask "jmactts" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "ccb8c6e57e5a8120f5d68902d18c5ea133935902fe75b5729b0facb17373b85f"
      url "https://github.com/junara/jmactts/releases/download/v#{version}/jmactts_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/junara/jmactts/"
    end
    on_arm do
      sha256 "972eec82a16b8fae431a27aec01b4cd0937ee01605c82db93a7f955addf67de7"
      url "https://github.com/junara/jmactts/releases/download/v#{version}/jmactts_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/junara/jmactts/"
    end
  end

  name "jmactts"
  desc "macOS multilingual text-to-speech CLI wrapping the `say` command"
  homepage "https://github.com/junara/jmactts"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jmactts"

  # No zap stanza required

end
