# This file was generated by slug-cli's release workflow. DO NOT EDIT.
cask "slug" do
  version "0.1.0"
  sha256 "04b0f824913c1090549d94e9ea4119ca0ad98d8cf60f4a17e16bc55e31ab386f"

  url "https://github.com/junara/slug-cli/releases/download/v#{version}/slug_#{version}_darwin_arm64.tar.gz"
  name "slug"
  desc "Generate an English URL slug from a Japanese title"
  homepage "https://github.com/junara/slug-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  # Apple Foundation Models を直接使うため、Apple silicon の macOS 26 以降が要る。
  depends_on arch: :arm64
  depends_on macos: :tahoe

  binary "slug"

  # 署名・公証をしていないため、Gatekeeper の隔離属性を外す。
  # postflight は deprecated なので postflight_steps を使う。
  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{staged_path}}/slug"]
  end

  # No zap stanza required
end
